const assert = require('node:assert/strict');
const { execFileSync, spawn } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');

const scriptsDirectory = __dirname; // Copy the scripts under test into each isolated repository.

function command(commandName, args, cwd, options = {}) {
  try {
    const stdout = execFileSync(commandName, args, {
      cwd,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      ...options
    });
    return { status: 0, output: stdout };
  } catch (error) {
    return {
      status: error.status ?? 1,
      output: `${error.stdout || ''}${error.stderr || ''}`
    };
  }
}

function git(cwd, ...args) {
  return execFileSync('git', args, { cwd, encoding: 'utf8' }).trim();
}

function createRepository() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'codex-release-test-'));
  fs.mkdirSync(path.join(root, 'scripts'));
  fs.mkdirSync(path.join(root, 'src-tauri'));
  fs.mkdirSync(path.join(root, 'src-tauri', 'src'));

  for (const filename of ['bump-version.cjs', 'git-utils.cjs', 'preversion.cjs', 'release.cjs']) {
    fs.copyFileSync(path.join(scriptsDirectory, filename), path.join(root, 'scripts', filename));
  }

  fs.writeFileSync(
    path.join(root, 'package.json'),
    JSON.stringify(
      {
        name: 'release-test',
        version: '1.0.0',
        private: true,
        scripts: {
          bump: 'node scripts/bump-version.cjs',
          release: 'node scripts/release.cjs',
          preversion: 'node scripts/preversion.cjs'
        }
      },
      null,
      2
    ) + '\n'
  );
  fs.writeFileSync(
    path.join(root, 'pnpm-lock.yaml'),
    "lockfileVersion: '9.0'\n\nsettings:\n  autoInstallPeers: true\n  excludeLinksFromLockfile: false\n\nimporters:\n\n  .: {}\n"
  );
  fs.writeFileSync(path.join(root, '.gitignore'), 'node_modules/\n');
  fs.writeFileSync(path.join(root, 'changelog.json'), '{}\n');
  fs.writeFileSync(path.join(root, 'src-tauri', 'tauri.conf.json'), '{\n  "version": "1.0.0"\n}\n');
  fs.writeFileSync(
    path.join(root, 'src-tauri', 'Cargo.toml'),
    '[package]\nname = "codex-usage-desktop"\nversion = "1.0.0"\nedition = "2021"\n'
  );
  fs.writeFileSync(
    path.join(root, 'src-tauri', 'Cargo.lock'),
    '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "codex-usage-desktop"\nversion = "1.0.0"\n'
  );
  fs.writeFileSync(path.join(root, 'src-tauri', 'src', 'main.rs'), 'fn main() {}\n');

  git(root, 'init', '-q');
  git(root, 'config', 'user.name', 'Release Test');
  git(root, 'config', 'user.email', 'release@example.com');
  git(root, 'add', '.');
  git(root, 'commit', '-qm', 'initial');
  git(root, 'tag', '-a', 'app-v1.0.0', '-m', 'app-v1.0.0');
  return root;
}

function runRelease(root, version) {
  return command(process.execPath, ['scripts/release.cjs', version], root);
}

function runPnpm(root, ...args) {
  const pnpmCli = process.env.npm_execpath;
  if (pnpmCli && /^pnpm(?:\.[cm]?js)?$/i.test(path.basename(pnpmCli))) {
    return command(process.execPath, [pnpmCli, ...args], root);
  }
  return command(process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm', args, root, {
    shell: process.platform === 'win32'
  });
}

function assertRelease(root, version) {
  assert.equal(JSON.parse(fs.readFileSync(path.join(root, 'package.json'))).version, version);
  assert.ok(JSON.parse(fs.readFileSync(path.join(root, 'changelog.json')))[version]);
  assert.equal(JSON.parse(fs.readFileSync(path.join(root, 'src-tauri', 'tauri.conf.json'))).version, version);
  assert.match(fs.readFileSync(path.join(root, 'src-tauri', 'Cargo.toml'), 'utf8'), new RegExp(`version = "${version}"`));
  assert.match(fs.readFileSync(path.join(root, 'src-tauri', 'Cargo.lock'), 'utf8'), new RegExp(`version = "${version}"`));
  assert.equal(git(root, 'log', '-1', '--format=%s'), version);
  assert.equal(git(root, 'cat-file', '-t', `refs/tags/app-v${version}`), 'tag');
  assert.deepEqual(
    git(root, 'show', '--pretty=format:', '--name-only', 'HEAD').split('\n').filter(Boolean).sort(),
    ['changelog.json', 'package.json', 'src-tauri/Cargo.lock', 'src-tauri/Cargo.toml', 'src-tauri/tauri.conf.json']
  );
  assert.equal(git(root, 'status', '--porcelain'), '');
}

test('releases a minor version with one commit and annotated tag', () => {
  const root = createRepository();
  const result = runPnpm(root, 'release', 'minor');
  assert.equal(result.status, 0, result.output);
  assertRelease(root, '1.1.0');
});

test('releases an explicit stable version', () => {
  const root = createRepository();
  const result = runRelease(root, '1.2.3');
  assert.equal(result.status, 0, result.output);
  assertRelease(root, '1.2.3');
});

test('rejects invalid, unchanged, and lower versions before rewriting files', () => {
  for (const version of ['next', '1.0.0-beta.1', '01.1.0', '1.0.0', '0.9.9']) {
    const root = createRepository();
    const before = fs.readFileSync(path.join(root, 'package.json'), 'utf8');
    const result = runRelease(root, version);
    assert.notEqual(result.status, 0, `${version} unexpectedly succeeded`);
    assert.equal(fs.readFileSync(path.join(root, 'package.json'), 'utf8'), before);
    assert.equal(git(root, 'status', '--porcelain'), '');
  }
});

test('rejects dirty worktrees and duplicate tags before rewriting files', () => {
  const dirtyRoot = createRepository();
  const dirtyBefore = fs.readFileSync(path.join(dirtyRoot, 'package.json'), 'utf8');
  fs.writeFileSync(path.join(dirtyRoot, 'untracked.txt'), 'dirty\n');
  const dirtyResult = runRelease(dirtyRoot, 'minor');
  assert.notEqual(dirtyResult.status, 0);
  assert.match(dirtyResult.output, /working tree must be clean/i);
  assert.equal(fs.readFileSync(path.join(dirtyRoot, 'package.json'), 'utf8'), dirtyBefore);

  const taggedRoot = createRepository();
  git(taggedRoot, 'tag', '-a', 'app-v1.1.0', '-m', 'app-v1.1.0');
  const taggedBefore = fs.readFileSync(path.join(taggedRoot, 'package.json'), 'utf8');
  const taggedResult = runRelease(taggedRoot, 'minor');
  assert.notEqual(taggedResult.status, 0);
  assert.match(taggedResult.output, /tag app-v1\.1\.0 already exists/i);
  assert.equal(fs.readFileSync(path.join(taggedRoot, 'package.json'), 'utf8'), taggedBefore);
});

test('waits for a transient index lock and succeeds', async () => {
  const root = createRepository();
  const lockPath = path.join(root, '.git', 'index.lock');

  const child = spawn(process.execPath, ['scripts/release.cjs', 'minor'], {
    cwd: root,
    stdio: ['ignore', 'pipe', 'pipe']
  });
  let output = '';
  let lockCreated = false;
  let unlockScheduled = false;
  child.stdout.on('data', chunk => {
    output += chunk;
    if (!lockCreated && output.includes('Updating src-tauri/Cargo.lock')) {
      fs.writeFileSync(lockPath, '');
      lockCreated = true;
    }
  });
  child.stderr.on('data', chunk => {
    output += chunk;
    if (!unlockScheduled && output.includes('Git index is locked; retrying')) {
      unlockScheduled = true;
      setTimeout(() => fs.unlinkSync(lockPath), 350);
    }
  });
  const status = await new Promise(resolve => child.on('close', resolve));

  assert.equal(status, 0, output);
  assert.match(output, /Git index is locked; retrying/);
  assertRelease(root, '1.1.0');
});

test('gives up on a persistent index lock without deleting it', () => {
  const root = createRepository();
  const lockPath = path.join(root, '.git', 'index.lock');
  fs.writeFileSync(lockPath, '');

  const result = runRelease(root, 'minor');

  assert.notEqual(result.status, 0);
  assert.match(result.output, /check for an active Git process/i);
  assert.equal(fs.existsSync(lockPath), true);
});

test('blocks pnpm version before package.json changes', () => {
  const root = createRepository();
  const before = fs.readFileSync(path.join(root, 'package.json'), 'utf8');
  const hookResult = command(process.execPath, ['scripts/preversion.cjs'], root);
  const result = runPnpm(root, 'version', 'minor');

  assert.notEqual(hookResult.status, 0);
  assert.match(hookResult.output, /pnpm version is disabled/i);
  assert.notEqual(result.status, 0);
  assert.equal(fs.readFileSync(path.join(root, 'package.json'), 'utf8'), before);
  assert.equal(git(root, 'status', '--porcelain'), '');
});

test('tauri.conf.json security CSP allows self, data:, and blob: images without wildcards', () => {
  const confPath = path.join(__dirname, '..', 'src-tauri', 'tauri.conf.json');
  const conf = JSON.parse(fs.readFileSync(confPath, 'utf8'));
  const csp = conf.app?.security?.csp;
  assert.ok(csp, 'CSP must be configured and not null');
  assert.equal(typeof csp, 'string');
  assert.doesNotMatch(csp, /img-src\s+\*/, 'img-src must not be wildcard');
  assert.doesNotMatch(csp, /default-src\s+\*/, 'default-src must not be wildcard');
  assert.match(csp, /img-src[^;]*'self'/, "img-src must include 'self'");
  assert.match(csp, /img-src[^;]*data:/, 'img-src must include data:');
  assert.match(csp, /img-src[^;]*blob:/, 'img-src must include blob:');
});
